### ISSUE TITLE
Handling of plays without any year information

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#154]
Currently, we have 5 plays without any year information, which makes it impossible to provide a "normalized year". In the frontend, they are listed on top of the chronological order with the year information "NaN". We should translate this into something that's easier to understand, either a simple dash ("–") or something like "not available".

The second aspect are the consequences for calculating with that data. This R script …

```
library(jsonlite)
einakter <- fromJSON("https://einakter.dracor.org/data.json")
hist(einakter$normalizedYear, breaks = 20, xlab="Jahrfünft", ylab="Anzahl Stücke im Korpus")
```

… yields an error message ("'x' muss numerisch sein"). The desired behaviour would be that plays without year information are neglected when plotting with year info – should this happen on the level of the scripts or could our API support this somehow?

**Comment by cmil** [comment]
I changed the text that is displayed in the table to "not available" (see 
ca85ec0). This would have to be translated in the language files. 

For the second aspect, I think it should be the responsibility or the R script to filter out plays without a normalised year. Those plays currently have `"normalizedYear": null` in data.json (see `jq '.[] | select(.normalizedYear == null)' < data.json`).

There are, however, currently also three plays for which the normalised year is a string (see `jq '.[] | select(.normalizedYear > "1")' < data.json`). This is because these entries have a  date string in their `created` or `printed` attribute where a number for the year only is actually expected.

**Comment by lehkost** [comment]
Thanks for spotting these three mistakes, fixed in https://github.com/dracor-org/einakter/commit/304289b803b07dcbba860d31e88f1cc1b4804768. The R script I posted now works fine again.

I will also collect the missing language strings for 'not available'.

**Comment by lehkost** [comment]
Ok, language strings for "n/a" are complete, let's close this ticket.
