### ISSUE TITLE
Collect author images, crunch them, store them

### ISSUE THREAD

**Issue by lehkost** [dracor-org/einakter#36]
(This feature request requires ticket #35 resolved.)

Just like with locations, we could sporadically fetch/update author images from Wikidata using the image information stored in the future ```src/authors.json```.

Storing them locally would have the advantage to resize them to our preferred image size, reducing traffic and making the page load faster, and we would not be dependent on Wikimedia Commons.

Author images (one file per author, as stored in "authors.json") could be put into a local ```/img/``` folder, using Q numbers as file names (e.g., "Q65863.jpg").

I propose to use ImageMagick (or a similar command-line tool) to make sure all images (PNG, GIF, etc.) are stored in JPG format. I would also reduce pictures to a fixed size (maybe height = 250px, with volatile widths).

**Comment by cmil** [comment]
In an MVP spirit I would prefer not to do that. We should be able to handle sizing issues for display in CSS. For the foreseeable future I don't see that we would create traffic of a proportion that would be an unfair burden for the wikimedia servers. Even if that becomes an issue, I would prefer to just create a proxy cache on our server. I would also expect that the wikimedia servers are better optimised for high traffic than our current hosting environment so that I'd be afraid that the page load times could even deteriorate if we would host the images ourselves.

**Comment by lehkost** [comment]
Agreed in the MVP spirit. 😊 On the long run, I think, there's still advantages of being independent from displaying content from other services, though, but definitely something we can postpone.

**Comment by cmil** [comment]
With the implementation in #63 we don't need this anymore. Can we close this issue then, @lehkost?
